set -g prefix C-a
bind C-a send-prefix

set -g mouse on
set -s escape-time 0
set -g repeat-time 50
set -g history-limit 50000

set -g base-index 1
setw -g pane-base-index 1

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

set -g default-terminal "tmux-256color"
set -g pane-active-border-style 'fg=color252'
set -g pane-border-style 'fg=color244'

set -g status on
set -g status-position bottom
set -g status-style 'fg=color232 bg=color253'
